#!/usr/bin/env python3
"""Generate the D0 selection-independence audit.

The input YAML is deliberately compact and machine-readable. This script emits
human-readable Markdown plus TSV so the current AN-dependence state can be
reviewed without rescanning long analysis notes.
"""

from __future__ import annotations

import argparse
import csv
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

import yaml


DEFAULT_CONFIG = Path("research/cms-d0-analysis/config/selection_independence.yaml")
DEFAULT_OUTDIR = Path("research/cms-d0-analysis/output/selection-independence")

STATUS_ORDER = ["independent", "partially_independent", "an_specification", "blocked"]
STATUS_LABEL = {
    "independent": "independent",
    "partially_independent": "partially independent",
    "an_specification": "AN specification",
    "blocked": "blocked",
}
STATUS_SCORE = {
    "independent": 3,
    "partially_independent": 2,
    "an_specification": 1,
    "blocked": 0,
}
RISK_SCORE = {"low": 1, "medium": 2, "high": 3}


def load_yaml(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    if not isinstance(data, dict):
        raise SystemExit(f"Config did not parse as a mapping: {path}")
    return data


def rows(data: dict[str, Any]) -> list[dict[str, Any]]:
    elements = data.get("selection_elements", [])
    if not isinstance(elements, list):
        raise SystemExit("selection_elements must be a list")
    required = {
        "id",
        "group",
        "item",
        "status",
        "current_definition",
        "a_priori_basis",
        "an_use",
        "overfit_risk",
        "next_action",
    }
    out: list[dict[str, Any]] = []
    seen: set[str] = set()
    for idx, row in enumerate(elements, start=1):
        if not isinstance(row, dict):
            raise SystemExit(f"selection_elements[{idx}] is not a mapping")
        missing = sorted(required - set(row))
        if missing:
            raise SystemExit(f"{row.get('id', idx)} missing fields: {', '.join(missing)}")
        ident = str(row["id"])
        if ident in seen:
            raise SystemExit(f"duplicate selection id: {ident}")
        seen.add(ident)
        status = str(row["status"])
        if status not in STATUS_SCORE:
            raise SystemExit(f"{ident}: unknown status {status}")
        risk = str(row["overfit_risk"])
        if risk not in RISK_SCORE:
            raise SystemExit(f"{ident}: unknown overfit_risk {risk}")
        out.append(row)
    return out


def priority(row: dict[str, Any]) -> tuple[int, int, str]:
    return (-RISK_SCORE[str(row["overfit_risk"])], STATUS_SCORE[str(row["status"])], str(row["id"]))


def write_tsv(path: Path, items: list[dict[str, Any]]) -> None:
    fields = [
        "id",
        "group",
        "item",
        "status",
        "overfit_risk",
        "current_definition",
        "a_priori_basis",
        "an_use",
        "next_action",
    ]
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, delimiter="\t", lineterminator="\n", extrasaction="ignore")
        writer.writeheader()
        for item in items:
            writer.writerow({field: item.get(field, "") for field in fields})


def md_escape(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def write_markdown(path: Path, data: dict[str, Any], items: list[dict[str, Any]]) -> None:
    counts = Counter(str(row["status"]) for row in items)
    risk_counts = Counter(str(row["overfit_risk"]) for row in items)
    by_group: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for item in items:
        by_group[str(item["group"])].append(item)

    high_priority = [
        row
        for row in sorted(items, key=priority)
        if str(row["status"]) != "independent" or str(row["overfit_risk"]) == "high"
    ][:8]

    policy = data.get("policy", {})
    with path.open("w", encoding="utf-8") as out:
        out.write("# D0 Selection-Independence Audit\n\n")
        out.write("<!-- DOC_OWNER: cms-analysis-manager selection-independence audit. -->\n")
        out.write("<!-- TOKEN_NOTE: generated by scripts/audit_selection_independence.py. -->\n\n")
        out.write("## Policy\n\n")
        out.write(f"- AN values are allowed for selection freeze: `{str(policy.get('use_an_for_selection_freeze')).lower()}`.\n")
        out.write(f"- AN values are allowed for posthoc validation: `{str(policy.get('use_an_for_posthoc_validation')).lower()}`.\n")
        out.write(f"- Signal peak is blinded for cut optimization: `{str(policy.get('blind_signal_peak_for_cut_optimization')).lower()}`.\n")
        out.write("- Freeze order:\n")
        for step in policy.get("freeze_order", []):
            out.write(f"  - {step}\n")
        out.write("\n")

        out.write("## Summary\n\n")
        out.write("| status | count |\n|---|---:|\n")
        for status in STATUS_ORDER:
            out.write(f"| {STATUS_LABEL[status]} | {counts.get(status, 0)} |\n")
        out.write("\n")
        out.write("| overfit risk | count |\n|---|---:|\n")
        for risk in ["high", "medium", "low"]:
            out.write(f"| {risk} | {risk_counts.get(risk, 0)} |\n")
        out.write("\n")

        out.write("## Highest-Priority Independence Work\n\n")
        out.write("| id | status | risk | next action |\n|---|---|---|---|\n")
        for row in high_priority:
            out.write(
                f"| `{md_escape(row['id'])}` | {STATUS_LABEL[str(row['status'])]} | "
                f"{md_escape(row['overfit_risk'])} | {md_escape(row['next_action'])} |\n"
            )
        out.write("\n")

        for group in sorted(by_group):
            out.write(f"## {group.title()}\n\n")
            out.write("| id | item | status | risk | AN use | a-priori basis | next action |\n")
            out.write("|---|---|---|---|---|---|---|\n")
            for row in sorted(by_group[group], key=lambda r: str(r["id"])):
                out.write(
                    f"| `{md_escape(row['id'])}` | {md_escape(row['item'])} | "
                    f"{STATUS_LABEL[str(row['status'])]} | {md_escape(row['overfit_risk'])} | "
                    f"{md_escape(row['an_use'])} | {md_escape(row['a_priori_basis'])} | "
                    f"{md_escape(row['next_action'])} |\n"
                )
            out.write("\n")

        out.write("## Interpretation\n\n")
        out.write(
            "The goal is not to erase the AN as the reproduction target. The goal is to "
            "avoid using AN constants to choose cuts. A cut is considered safer when the "
            "rule, control sample, score, and rounding are frozen before comparing to the AN. "
            "If the blind rule lands on a nearby plateau point, the correct response is a "
            "closure/systematic comparison, not silent retuning to the AN.\n"
        )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--outdir", type=Path, default=DEFAULT_OUTDIR)
    args = parser.parse_args()

    data = load_yaml(args.config)
    items = rows(data)
    args.outdir.mkdir(parents=True, exist_ok=True)
    write_tsv(args.outdir / "selection_independence_audit.tsv", items)
    write_markdown(args.outdir / "selection_independence_audit.md", data, items)
    print(f"Wrote {args.outdir / 'selection_independence_audit.md'}")
    print(f"Wrote {args.outdir / 'selection_independence_audit.tsv'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
