#!/usr/bin/env python3
"""Build compact official MC sample tables from stored McM snapshots."""

from __future__ import annotations

import csv
import json
from datetime import datetime, timezone
from pathlib import Path

import yaml


WORKSPACE = Path(__file__).resolve().parents[1]
OUTDIR = WORKSPACE / "output" / "mc-sample-tables" / "official_mcm_20260621"
MCM_DIR = WORKSPACE / "output" / "mcm"
REGISTRY = WORKSPACE / "registry.yaml"


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))["results"]


def dataset_events(request: dict, suffix: str) -> tuple[str, int, str]:
    for req in request.get("reqmgr_name", []):
        content = req.get("content") or {}
        statuses = content.get("pdmv_dataset_statuses") or {}
        for dataset, status in statuses.items():
            if dataset.endswith(f"/{suffix}"):
                return dataset, int(status.get("pdmv_evts_in_DAS") or 0), str(status.get("pdmv_status_in_DAS") or "")
    return "", 0, ""


def registry_dataset_by_mcm() -> dict[str, dict]:
    data = yaml.safe_load(REGISTRY.read_text(encoding="utf-8"))
    rows = {}
    for item in data.get("datasets", []):
        req = item.get("mcm_request")
        if req:
            rows[req] = item
    return rows


def row_from_request(path: Path) -> dict[str, str]:
    request = load_json(path)
    prepid = request["prepid"]
    registry_rows = registry_dataset_by_mcm()
    registry = registry_rows.get(prepid, {})
    params = request.get("generator_parameters") or [{}]
    active_param = params[-1] if params else {}
    mini, mini_events, mini_status = dataset_events(request, "MINIAODSIM")
    aod, aod_events, aod_status = dataset_events(request, "AODSIM")
    flavor = "prompt" if "prompt-" in request.get("dataset_name", "") and "nonprompt" not in request.get("dataset_name", "") else "nonprompt"
    return {
        "flavor": flavor,
        "mcm_request": prepid,
        "status": str(request.get("status", "")),
        "dataset_name": str(request.get("dataset_name", "")),
        "cmssw_release": str(request.get("cmssw_release", "")),
        "total_events_requested": str(request.get("total_events", "")),
        "miniaod_events_in_das": str(mini_events),
        "miniaod_status": mini_status,
        "filter_efficiency": str(active_param.get("filter_efficiency", "")),
        "filter_efficiency_error": str(active_param.get("filter_efficiency_error", "")),
        "cross_section": str(active_param.get("cross_section", "")),
        "generators": ", ".join(request.get("generators", [])),
        "official_fragment": str(registry.get("official_fragment", "")),
        "local_reference_skim": str(registry.get("skim", "")),
        "miniaod_dataset": mini,
        "aod_events_in_das": str(aod_events),
        "aod_status": aod_status,
        "aod_dataset": aod,
    }


def write_markdown(rows: list[dict[str, str]], path: Path) -> None:
    lines = [
        "# Official MC Sample Tables",
        "",
        "<!-- DOC_OWNER: cms-analysis-manager generated MC sample table. -->",
        "<!-- TOKEN_NOTE: generated by build_official_mc_sample_tables.py. -->",
        "",
        f"Generated UTC: `{datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}`",
        "",
        "These rows are generated from stored McM snapshots and the local D0 registry. They document sample provenance; they do not by themselves define final correction weights.",
        "",
        "| Flavor | McM request | MINIAOD events | Filter efficiency | MINIAOD dataset |",
        "| --- | --- | ---: | ---: | --- |",
    ]
    for row in rows:
        lines.append(
            "| {flavor} | `{mcm_request}` | {miniaod_events_in_das} | {filter_efficiency} | `{miniaod_dataset}` |".format(**row)
        )
    lines.extend(
        [
            "",
            "## Caveats",
            "",
            "- Cross sections are not filled in these McM snapshots (`-1`), so final normalization still needs the analysis-specific correction chain.",
            "- The table currently covers the official prompt/nonprompt BeamA requests stored locally; direct/resolved and pThat stitching tables remain separate missing work.",
            "- Filter efficiencies are copied from the active McM generator-parameter entry.",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    OUTDIR.mkdir(parents=True, exist_ok=True)
    snapshots = sorted(MCM_DIR.glob("HIN-HINPbPbWinter24UPCGS-*.json"))
    rows = [row_from_request(path) for path in snapshots]
    fieldnames = list(rows[0].keys()) if rows else []
    if rows:
        with (OUTDIR / "official_mc_sample_table.tsv").open("w", newline="", encoding="utf-8") as handle:
            writer = csv.DictWriter(handle, fieldnames=fieldnames, delimiter="\t", lineterminator="\n")
            writer.writeheader()
            writer.writerows(rows)
    write_markdown(rows, OUTDIR / "README.md")
    print(f"wrote {OUTDIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
